insert into Departements (departementID, DepartementName)
values
('PT EigerIndo'),
('PT AlmasIndo'),
('PT  Eskol Jaya Persada');

insert into Projects (projectID, ProjectName, DepartementID)
values
('Payung ajaib', 1),
('Jilbab tak kasat mata', 1),
('Meriam kentang', 1),
('Ethernet wireless', 2),
('Hover Mouse', 2),
('Hologram', 2),
('Borgol setrum', 3),
('Alat mata-mata warga', 3),
('Budak Setengah Manusia Setengah Robot', 3),
('Bebek pembantu', 1)

insert into Employee (employeeID, Name, departementID, ManagerID)
values
('Endun', null, 1),
('Ayu Wandira', 1, Null),
('Kokom', 1, Null),
('Aan Bintayod', 1, Null),
('Ikah', 1, Null),
('Cecep', null, 2),
('Aan Darwati', 1, Null),
('Ayi Sutarya', null, 3),
('Anih', 1, Null),
('Yani Suminar', 1, Null),
('Dian', null, 1),
('Fitri', 2, Null),
('Wati Talwati', 2, Null),
('Tati Rasliati', null, 2),
('Wawan Saepudin', 2, Null),
('Karlina', 2, Null),
('Popon Patimah', null, 3),
('Herlina', 2, Null),
('Unah', 2, Null),
('Erwin Rambe', 2, Null),
('Ida Mulyanah', null, 1),
('Oneng', 3, Null),
('Nining', 3, Null),
('Elah Hayati', 3, Null),
('Wiwi', 3, Null),
('Ade Lela', 3, Null),
('Suryana', 3, Null),
('Jajang Sahidin', 3, Null),
('Eneng Angreni', 3, Null),
('Tini Sutini', null, 3);

insert into Salaries (employeeID, Salaries)
values
(1, 10),
(2, 20),
(3, 30),
(4, 40),
(5, 10),
(6, 10),
(7, 10),
(8, 10),
(9, 10),
(10, 10),
(11, 10),
(12, 10),
(13, 10),
(14, 10),
(15, 10),
(16, 10),
(17, 10),
(18, 10),
(19, 10),
(20, 10),
(21, 10),
(22, 10),
(23, 10),
(24, 10),
(25, 10),
(26, 10),
(27, 10),
(28, 10),
(29, 10),
(30, 10);